# Generated by Django 5.0.4 on 2024-04-22 20:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_rename_account_accountnew_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accountnew',
            new_name='Account',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='balancenew',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='usernew',
            new_name='user',
        ),
    ]
