# Generated by Django 5.0.4 on 2024-04-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_rename_accountnew_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_currency', models.CharField(max_length=3)),
                ('target_currency', models.CharField(max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
    ]
