# Generated by Django 5.0.4 on 2024-04-25 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_delete_currencyconversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
