# Generated by Django 5.0.4 on 2024-05-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_paymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
